"use client";

import { useEffect, useState } from "react";
import { toast } from "sonner";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/Card";
import { Input } from "@/components/ui/Input";
import { cn } from "@/lib/utils";

const tabs = [
  { key: "aboutUs", label: "About Us" },
  { key: "contactUs", label: "Contact Us" },
  { key: "privacyPolicy", label: "Privacy Policy" },
  { key: "termsOfService", label: "Terms of Service" },
  { key: "sitemap", label: "Sitemap" },
];

const defaultContent = {
  aboutUs: {
    heroBadge: "Our Story",
    heroTitleLine1: "We killed the",
    heroTitleAccent: "expired code.",
    heroDescription: "",
    statVerifiedStores: "",
    statMonthlyUsers: "",
    statCodeAccuracy: "",
    statActiveDeals: "",
    missionQuote: "",
    missionParagraph1: "",
    missionParagraph2: "",
    promiseTitle: "The Promise",
    promiseDescription: "",
    promiseBullet1: "",
    promiseBullet2: "",
    promiseBullet3: "",
    ctaEyebrow: "Start Saving Today",
    ctaTitleLine1: "Every code. Verified.",
    ctaTitleAccent: "Every time.",
    ctaDescription: "",
  },
  contactUs: {
    title: "Contact Us",
    subtitle: "We'd love to hear from you.",
    email: "",
    phone: "",
    address: "",
    businessHours: "",
    formEnabled: true,
    formNote: "",
  },
  privacyPolicy: {
    title: "Privacy Policy",
    lastUpdated: "",
    content: "",
  },
  termsOfService: {
    title: "Terms of Service",
    lastUpdated: "",
    content: "",
  },
  sitemap: {
    title: "Sitemap",
    subtitle: "",
    showAutoGeneratedStores: true,
    showAutoGeneratedCategories: true,
    showBlogSection: true,
    customLinks: [],
  },
};

function FieldLabel({ children }) {
  return (
    <span className="text-xs font-bold uppercase tracking-wider text-[var(--text)]">
      {children}
    </span>
  );
}

function FieldRow({ label, hint, children }) {
  return (
    <label className="grid gap-2">
      <FieldLabel>{label}</FieldLabel>
      {children}
      {hint ? <span className="text-[11px] text-[var(--muted)] leading-relaxed">{hint}</span> : null}
    </label>
  );
}

function StyledInput({ ...props }) {
  return (
    <Input
      className="h-11 rounded-xl border-[var(--border)] bg-[var(--surface-soft)] px-4 text-sm text-[var(--text)] placeholder:text-[var(--muted)] focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/10"
      {...props}
    />
  );
}

function StyledTextarea({ rows = 6, ...props }) {
  return (
    <textarea
      rows={rows}
      className="w-full rounded-xl border border-[var(--border)] bg-[var(--surface-soft)] px-4 py-3 text-sm text-[var(--text)] outline-none transition placeholder:text-[var(--muted)] focus:border-[var(--color-primary)] focus:ring-2 focus:ring-[var(--color-primary)]/10 resize-y"
      {...props}
    />
  );
}

function ToggleRow({ label, description, checked, onChange }) {
  return (
    <label className="flex h-12 items-center justify-between rounded-xl border border-[var(--border)] bg-[var(--surface-soft)]/60 px-4 text-xs cursor-pointer hover:bg-[var(--surface-soft)] transition-colors">
      <div>
        <span className="font-bold text-[var(--text)]">{label}</span>
        {description ? <span className="block text-[11px] text-[var(--muted)]">{description}</span> : null}
      </div>
      <input
        type="checkbox"
        className="accent-[var(--color-primary)] h-4 w-4 cursor-pointer"
        checked={checked}
        onChange={onChange}
      />
    </label>
  );
}

export default function AdminCompanyManager() {
  const [content, setContent] = useState(defaultContent);
  const [isLoading, setIsLoading] = useState(true);
  const [savingTab, setSavingTab] = useState("");
  const [activeTab, setActiveTab] = useState("aboutUs");

  useEffect(() => {
    let active = true;

    async function load() {
      try {
        const res = await fetch("/api/company", { cache: "no-store" });
        const payload = await res.json();
        if (!res.ok) throw new Error(payload.error || "Unable to load company content.");
        if (active) setContent(payload.data);
      } catch (err) {
        toast.error(err.message);
      } finally {
        if (active) setIsLoading(false);
      }
    }

    load();
    return () => { active = false; };
  }, []);

  function update(section, field, value) {
    setContent((prev) => ({
      ...prev,
      [section]: { ...prev[section], [field]: value },
    }));
  }

  async function saveTab(tabKey, tabLabel) {
    try {
      setSavingTab(tabKey);
      const res = await fetch("/api/company", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ [tabKey]: content[tabKey] }),
      });
      const payload = await res.json();
      if (!res.ok) throw new Error(payload.error || "Unable to save.");
      setContent(payload.data);
      toast.success(`${tabLabel} saved.`);
    } catch (err) {
      toast.error(err.message);
    } finally {
      setSavingTab("");
    }
  }

  if (isLoading) {
    return (
      <Card>
        <CardContent className="py-12 text-center text-xs text-[var(--muted)]">Loading company content...</CardContent>
      </Card>
    );
  }

  return (
    <div className="space-y-6">
      {/* Tab Bar */}
      <Card>
        <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
          <div>
            <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">Company Pages</CardTitle>
            <CardDescription className="text-xs text-[var(--muted)] mt-0.5">
              Manage content for all company pages. Changes are saved per section.
            </CardDescription>
          </div>
        </CardHeader>
        <CardContent className="p-6">
          <div className="flex flex-wrap gap-2">
            {tabs.map((tab) => (
              <button
                key={tab.key}
                type="button"
                className={cn(
                  "rounded-full px-4 py-1.5 text-xs font-bold transition-all duration-150",
                  activeTab === tab.key
                    ? "bg-[var(--color-primary)] text-white shadow-sm"
                    : "border border-[var(--border)] bg-[var(--surface)] text-[var(--muted)] hover:text-[var(--text)] hover:border-[var(--color-primary)]/40"
                )}
                onClick={() => setActiveTab(tab.key)}
              >
                {tab.label}
              </button>
            ))}
          </div>
        </CardContent>
      </Card>

      {/* About Us */}
      {activeTab === "aboutUs" ? (
        <Card>
          <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
            <div>
              <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">About Us</CardTitle>
              <CardDescription className="text-xs text-[var(--muted)] mt-0.5">Company introduction and identity.</CardDescription>
            </div>
            <button
              type="button"
              onClick={() => saveTab("aboutUs", "About Us")}
              disabled={savingTab === "aboutUs"}
              className="inline-flex h-10 items-center justify-center rounded-xl bg-[var(--color-primary)] hover:bg-[var(--color-primary-hover)] px-5 text-xs font-bold text-white shadow-sm transition-all duration-200 cursor-pointer disabled:opacity-60 flex-shrink-0"
            >
              {savingTab === "aboutUs" ? "Saving…" : "Save"}
            </button>
          </CardHeader>
          <CardContent className="p-6 grid gap-6 md:grid-cols-2">
            {/* HERO SECTION */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-4 mt-2">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">Hero Section</h3>
            </div>
            <FieldRow label="Hero Badge Text">
              <StyledInput value={content.aboutUs.heroBadge} onChange={(e) => update("aboutUs", "heroBadge", e.target.value)} placeholder="Our Story" />
            </FieldRow>
            <FieldRow label="Hero Title (Part 1)">
              <StyledInput value={content.aboutUs.heroTitleLine1} onChange={(e) => update("aboutUs", "heroTitleLine1", e.target.value)} placeholder="We killed the" />
            </FieldRow>
            <FieldRow label="Hero Title Accent (Purple)">
              <StyledInput value={content.aboutUs.heroTitleAccent} onChange={(e) => update("aboutUs", "heroTitleAccent", e.target.value)} placeholder="expired code." />
            </FieldRow>
            <div className="md:col-span-2">
              <FieldRow label="Hero Description">
                <StyledTextarea rows={3} value={content.aboutUs.heroDescription} onChange={(e) => update("aboutUs", "heroDescription", e.target.value)} placeholder="Couponchy was built out of frustration..." />
              </FieldRow>
            </div>

            {/* STATS SECTION */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-4 mt-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">Stats Section</h3>
            </div>
            <FieldRow label="Verified Stores count" hint="Leave blank to pull dynamically from database.">
              <StyledInput value={content.aboutUs.statVerifiedStores || ""} onChange={(e) => update("aboutUs", "statVerifiedStores", e.target.value)} placeholder="e.g. 263+" />
            </FieldRow>
            <FieldRow label="Monthly Users count">
              <StyledInput value={content.aboutUs.statMonthlyUsers || ""} onChange={(e) => update("aboutUs", "statMonthlyUsers", e.target.value)} placeholder="e.g. 1.34M+" />
            </FieldRow>
            <FieldRow label="Code Accuracy percentage">
              <StyledInput value={content.aboutUs.statCodeAccuracy || ""} onChange={(e) => update("aboutUs", "statCodeAccuracy", e.target.value)} placeholder="e.g. 98%" />
            </FieldRow>
            <FieldRow label="Active Deals count" hint="Leave blank to pull dynamically from database.">
              <StyledInput value={content.aboutUs.statActiveDeals || ""} onChange={(e) => update("aboutUs", "statActiveDeals", e.target.value)} placeholder="e.g. 654+" />
            </FieldRow>

            {/* MISSION SECTION */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-4 mt-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">Mission Section</h3>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Mission Quote" hint="Shown in quotes at the left side of the mission section.">
                <StyledInput value={content.aboutUs.missionQuote} onChange={(e) => update("aboutUs", "missionQuote", e.target.value)} placeholder="Nobody should waste money on a coupon that doesn't work." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Mission Paragraph 1">
                <StyledTextarea rows={3} value={content.aboutUs.missionParagraph1} onChange={(e) => update("aboutUs", "missionParagraph1", e.target.value)} placeholder="We started Couponchy because we kept getting burned..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Mission Paragraph 2">
                <StyledTextarea rows={3} value={content.aboutUs.missionParagraph2} onChange={(e) => update("aboutUs", "missionParagraph2", e.target.value)} placeholder="So we built a real-time verification engine..." />
              </FieldRow>
            </div>

            {/* PROMISE CARD SECTION */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-4 mt-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">The Promise Card</h3>
            </div>
            <FieldRow label="Promise Card Title">
              <StyledInput value={content.aboutUs.promiseTitle} onChange={(e) => update("aboutUs", "promiseTitle", e.target.value)} placeholder="The Promise" />
            </FieldRow>
            <FieldRow label="Promise Bullet 1">
              <StyledInput value={content.aboutUs.promiseBullet1} onChange={(e) => update("aboutUs", "promiseBullet1", e.target.value)} placeholder="Real-time code verification" />
            </FieldRow>
            <FieldRow label="Promise Bullet 2">
              <StyledInput value={content.aboutUs.promiseBullet2} onChange={(e) => update("aboutUs", "promiseBullet2", e.target.value)} placeholder="Auto-removal of expired deals" />
            </FieldRow>
            <FieldRow label="Promise Bullet 3">
              <StyledInput value={content.aboutUs.promiseBullet3} onChange={(e) => update("aboutUs", "promiseBullet3", e.target.value)} placeholder="Zero fake or misleading discounts" />
            </FieldRow>
            <div className="md:col-span-2">
              <FieldRow label="Promise Card Description">
                <StyledTextarea rows={3} value={content.aboutUs.promiseDescription} onChange={(e) => update("aboutUs", "promiseDescription", e.target.value)} placeholder="Every coupon you see on Couponchy has been verified..." />
              </FieldRow>
            </div>

            {/* CTA BANNER */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-4 mt-4">
              <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">CTA Banner Section</h3>
            </div>
            <FieldRow label="CTA Eyebrow">
              <StyledInput value={content.aboutUs.ctaEyebrow} onChange={(e) => update("aboutUs", "ctaEyebrow", e.target.value)} placeholder="Start Saving Today" />
            </FieldRow>
            <FieldRow label="CTA Title (Part 1)">
              <StyledInput value={content.aboutUs.ctaTitleLine1} onChange={(e) => update("aboutUs", "ctaTitleLine1", e.target.value)} placeholder="Every code. Verified." />
            </FieldRow>
            <FieldRow label="CTA Title Accent (Purple)">
              <StyledInput value={content.aboutUs.ctaTitleAccent} onChange={(e) => update("aboutUs", "ctaTitleAccent", e.target.value)} placeholder="Every time." />
            </FieldRow>
            <div className="md:col-span-2">
              <FieldRow label="CTA Description">
                <StyledTextarea rows={3} value={content.aboutUs.ctaDescription} onChange={(e) => update("aboutUs", "ctaDescription", e.target.value)} placeholder="Browse our verified stores and start saving..." />
              </FieldRow>
            </div>
          </CardContent>
        </Card>
      ) : null}

      {/* Contact Us */}
      {activeTab === "contactUs" ? (
        <Card>
          <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
            <div>
              <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">Contact Us</CardTitle>
              <CardDescription className="text-xs text-[var(--muted)] mt-0.5">Contact page text and business details.</CardDescription>
            </div>
            <button
              type="button"
              onClick={() => saveTab("contactUs", "Contact Us")}
              disabled={savingTab === "contactUs"}
              className="inline-flex h-10 items-center justify-center rounded-xl bg-[var(--color-primary)] hover:bg-[var(--color-primary-hover)] px-5 text-xs font-bold text-white shadow-sm transition-all duration-200 cursor-pointer disabled:opacity-60 flex-shrink-0"
            >
              {savingTab === "contactUs" ? "Saving…" : "Save"}
            </button>
          </CardHeader>
          <CardContent className="p-6 grid gap-5 md:grid-cols-2">
            <FieldRow label="Page Title">
              <StyledInput value={content.contactUs.title} onChange={(e) => update("contactUs", "title", e.target.value)} placeholder="Contact Us" />
            </FieldRow>
            <FieldRow label="Subtitle">
              <StyledInput value={content.contactUs.subtitle} onChange={(e) => update("contactUs", "subtitle", e.target.value)} placeholder="We'd love to hear from you." />
            </FieldRow>
            <FieldRow label="Support Email">
              <StyledInput type="email" value={content.contactUs.email} onChange={(e) => update("contactUs", "email", e.target.value)} placeholder="support@couponchy.com" />
            </FieldRow>
            <FieldRow label="Phone Number">
              <StyledInput value={content.contactUs.phone} onChange={(e) => update("contactUs", "phone", e.target.value)} placeholder="+1 (800) 000-0000" />
            </FieldRow>
            <FieldRow label="Business Hours">
              <StyledInput value={content.contactUs.businessHours} onChange={(e) => update("contactUs", "businessHours", e.target.value)} placeholder="Monday – Friday, 9am – 6pm" />
            </FieldRow>
            <FieldRow label="Office Address">
              <StyledInput value={content.contactUs.address} onChange={(e) => update("contactUs", "address", e.target.value)} placeholder="123 Main St, New York, NY" />
            </FieldRow>
            <div className="md:col-span-2">
              <ToggleRow
                label="Enable Contact Form"
                description="Show a contact form on the public Contact Us page."
                checked={Boolean(content.contactUs.formEnabled)}
                onChange={(e) => update("contactUs", "formEnabled", e.target.checked)}
              />
            </div>
            <FieldRow label="Form Note" hint="Short text shown above the contact form." className="md:col-span-2">
              <StyledTextarea rows={2} value={content.contactUs.formNote} onChange={(e) => update("contactUs", "formNote", e.target.value)} placeholder="Fill out the form and we'll get back to you within 24 hours." />
            </FieldRow>
          </CardContent>
        </Card>
      ) : null}

      {/* Privacy Policy */}
      {activeTab === "privacyPolicy" ? (
        <Card>
          <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
            <div>
              <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">Privacy Policy</CardTitle>
              <CardDescription className="text-xs text-[var(--muted)] mt-0.5">Legal privacy policy content for your platform.</CardDescription>
            </div>
            <button
              type="button"
              onClick={() => saveTab("privacyPolicy", "Privacy Policy")}
              disabled={savingTab === "privacyPolicy"}
              className="inline-flex h-10 items-center justify-center rounded-xl bg-[var(--color-primary)] hover:bg-[var(--color-primary-hover)] px-5 text-xs font-bold text-white shadow-sm transition-all duration-200 cursor-pointer disabled:opacity-60 flex-shrink-0"
            >
              {savingTab === "privacyPolicy" ? "Saving…" : "Save"}
            </button>
          </CardHeader>
           <CardContent className="p-6 grid gap-6 md:grid-cols-2">
            <FieldRow label="Page Title">
              <StyledInput value={content.privacyPolicy.title} onChange={(e) => update("privacyPolicy", "title", e.target.value)} placeholder="Privacy Policy" />
            </FieldRow>
            <FieldRow label="Last Updated Date" hint="Shown at the top of the privacy page.">
              <StyledInput type="text" value={content.privacyPolicy.lastUpdated} onChange={(e) => update("privacyPolicy", "lastUpdated", e.target.value)} placeholder="March 2026" />
            </FieldRow>

            {/* SECTION 1 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">1. Introduction</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Introduction Text">
                <StyledTextarea rows={3} value={content.privacyPolicy.introText} onChange={(e) => update("privacyPolicy", "introText", e.target.value)} placeholder="Welcome to Couponchy..." />
              </FieldRow>
            </div>

            {/* SECTION 2 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">2. Information We Collect</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Main Description text">
                <StyledTextarea rows={2} value={content.privacyPolicy.collectText} onChange={(e) => update("privacyPolicy", "collectText", e.target.value)} placeholder="We prioritize your privacy and minimize data collection..." />
              </FieldRow>
            </div>
            <FieldRow label="Bullet 1 Title">
              <StyledInput value={content.privacyPolicy.collectBullet1Title} onChange={(e) => update("privacyPolicy", "collectBullet1Title", e.target.value)} placeholder="Voluntary Contact Info:" />
            </FieldRow>
            <FieldRow label="Bullet 1 Description">
              <StyledInput value={content.privacyPolicy.collectBullet1Desc} onChange={(e) => update("privacyPolicy", "collectBullet1Desc", e.target.value)} placeholder="Email address, name..." />
            </FieldRow>
            <FieldRow label="Bullet 2 Title">
              <StyledInput value={content.privacyPolicy.collectBullet2Title} onChange={(e) => update("privacyPolicy", "collectBullet2Title", e.target.value)} placeholder="Usage and Device Data:" />
            </FieldRow>
            <FieldRow label="Bullet 2 Description">
              <StyledInput value={content.privacyPolicy.collectBullet2Desc} onChange={(e) => update("privacyPolicy", "collectBullet2Desc", e.target.value)} placeholder="IP address, country..." />
            </FieldRow>

            {/* SECTION 3 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">3. How We Use Information</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Introductory Text">
                <StyledInput value={content.privacyPolicy.useText} onChange={(e) => update("privacyPolicy", "useText", e.target.value)} placeholder="We use collected information solely to:" />
              </FieldRow>
            </div>
            <FieldRow label="Use Case 1 (Card 1)">
              <StyledInput value={content.privacyPolicy.useGrid1} onChange={(e) => update("privacyPolicy", "useGrid1", e.target.value)} placeholder="Deliver regional storefront..." />
            </FieldRow>
            <FieldRow label="Use Case 2 (Card 2)">
              <StyledInput value={content.privacyPolicy.useGrid2} onChange={(e) => update("privacyPolicy", "useGrid2", e.target.value)} placeholder="Verify coupon submissions..." />
            </FieldRow>
            <FieldRow label="Use Case 3 (Card 3)">
              <StyledInput value={content.privacyPolicy.useGrid3} onChange={(e) => update("privacyPolicy", "useGrid3", e.target.value)} placeholder="Process and resolve support..." />
            </FieldRow>
            <FieldRow label="Use Case 4 (Card 4)">
              <StyledInput value={content.privacyPolicy.useGrid4} onChange={(e) => update("privacyPolicy", "useGrid4", e.target.value)} placeholder="Prevent fraud..." />
            </FieldRow>

            {/* SECTIONS 4 - 8 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">Remaining Policy Sections</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="4. Cookies and Tracking">
                <StyledTextarea rows={3} value={content.privacyPolicy.cookiesText} onChange={(e) => update("privacyPolicy", "cookiesText", e.target.value)} placeholder="We utilize cookies to remember your country..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="5. Data Protection">
                <StyledTextarea rows={3} value={content.privacyPolicy.dataSecurityText} onChange={(e) => update("privacyPolicy", "dataSecurityText", e.target.value)} placeholder="We apply industry-standard security measures..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="6. Third-Party Merchants">
                <StyledTextarea rows={3} value={content.privacyPolicy.thirdPartyText} onChange={(e) => update("privacyPolicy", "thirdPartyText", e.target.value)} placeholder="Our site lists deals and links to third-party..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="7. Your Privacy Rights">
                <StyledTextarea rows={3} value={content.privacyPolicy.userRightsText} onChange={(e) => update("privacyPolicy", "userRightsText", e.target.value)} placeholder="Depending on your localization, you possess rights..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="8. Changes to this Policy">
                <StyledTextarea rows={3} value={content.privacyPolicy.policyUpdatesText} onChange={(e) => update("privacyPolicy", "policyUpdatesText", e.target.value)} placeholder="We reserve the right to revise this Privacy..." />
              </FieldRow>
            </div>
          </CardContent>
        </Card>
      ) : null}

      {/* Terms of Service */}
      {activeTab === "termsOfService" ? (
        <Card>
          <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
            <div>
              <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">Terms of Service</CardTitle>
              <CardDescription className="text-xs text-[var(--muted)] mt-0.5">Legal terms and conditions for your platform.</CardDescription>
            </div>
            <button
              type="button"
              onClick={() => saveTab("termsOfService", "Terms of Service")}
              disabled={savingTab === "termsOfService"}
              className="inline-flex h-10 items-center justify-center rounded-xl bg-[var(--color-primary)] hover:bg-[var(--color-primary-hover)] px-5 text-xs font-bold text-white shadow-sm transition-all duration-200 cursor-pointer disabled:opacity-60 flex-shrink-0"
            >
              {savingTab === "termsOfService" ? "Saving…" : "Save"}
            </button>
          </CardHeader>
          <CardContent className="p-6 grid gap-6 md:grid-cols-2">
            <FieldRow label="Page Title">
              <StyledInput value={content.termsOfService.title} onChange={(e) => update("termsOfService", "title", e.target.value)} placeholder="Terms of Service" />
            </FieldRow>
            <FieldRow label="Last Updated Date" hint="Shown at the top of the terms page.">
              <StyledInput type="text" value={content.termsOfService.lastUpdated} onChange={(e) => update("termsOfService", "lastUpdated", e.target.value)} placeholder="March 2026" />
            </FieldRow>

            {/* SECTION 1 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-2">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">1. Acceptance of Terms</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Acceptance Description">
                <StyledTextarea rows={3} value={content.termsOfService.acceptanceText} onChange={(e) => update("termsOfService", "acceptanceText", e.target.value)} placeholder="By accessing the website..." />
              </FieldRow>
            </div>

            {/* SECTION 2 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">2. Use License</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="Use License Intro text">
                <StyledTextarea rows={2} value={content.termsOfService.licenseText} onChange={(e) => update("termsOfService", "licenseText", e.target.value)} placeholder="Permission is granted to temporarily view..." />
              </FieldRow>
            </div>
            <FieldRow label="Bullet 1 Description">
              <StyledInput value={content.termsOfService.licenseBullet1} onChange={(e) => update("termsOfService", "licenseBullet1", e.target.value)} placeholder="Modify or copy the materials..." />
            </FieldRow>
            <FieldRow label="Bullet 2 Description">
              <StyledInput value={content.termsOfService.licenseBullet2} onChange={(e) => update("termsOfService", "licenseBullet2", e.target.value)} placeholder="Use the materials for commercial purpose..." />
            </FieldRow>
            <FieldRow label="Bullet 3 Description">
              <StyledInput value={content.termsOfService.licenseBullet3} onChange={(e) => update("termsOfService", "licenseBullet3", e.target.value)} placeholder="Attempt to decompile or reverse engineer..." />
            </FieldRow>
            <FieldRow label="Bullet 4 Description">
              <StyledInput value={content.termsOfService.licenseBullet4} onChange={(e) => update("termsOfService", "licenseBullet4", e.target.value)} placeholder="Remove any copyright notations..." />
            </FieldRow>

            {/* SECTIONS 3 - 8 */}
            <div className="md:col-span-2 border-b border-[var(--border)] pb-2 mt-4">
              <h4 className="text-xs font-bold uppercase tracking-wider text-[var(--color-primary)]">Remaining Terms Sections</h4>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="3. Disclaimer of Accuracy">
                <StyledTextarea rows={3} value={content.termsOfService.disclaimerText} onChange={(e) => update("termsOfService", "disclaimerText", e.target.value)} placeholder="The materials on Couponchy are provided on an 'as is' basis..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="4. Limitations of Liability">
                <StyledTextarea rows={3} value={content.termsOfService.limitationsText} onChange={(e) => update("termsOfService", "limitationsText", e.target.value)} placeholder="In no event shall Couponchy or its suppliers be liable..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="5. Revisions and Errata">
                <StyledTextarea rows={3} value={content.termsOfService.revisionsText} onChange={(e) => update("termsOfService", "revisionsText", e.target.value)} placeholder="The materials appearing on Couponchy could include..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="6. External Links">
                <StyledTextarea rows={3} value={content.termsOfService.linksText} onChange={(e) => update("termsOfService", "linksText", e.target.value)} placeholder="We have not reviewed all of the sites linked..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="7. Terms Modifications">
                <StyledTextarea rows={3} value={content.termsOfService.modificationsText} onChange={(e) => update("termsOfService", "modificationsText", e.target.value)} placeholder="We may revise these terms of service..." />
              </FieldRow>
            </div>
            <div className="md:col-span-2">
              <FieldRow label="8. Governing Law">
                <StyledTextarea rows={3} value={content.termsOfService.governingLawText} onChange={(e) => update("termsOfService", "governingLawText", e.target.value)} placeholder="These terms and conditions are governed by..." />
              </FieldRow>
            </div>
          </CardContent>
        </Card>
      ) : null}

      {/* Sitemap */}
      {activeTab === "sitemap" ? (
        <Card>
          <CardHeader className="flex flex-col gap-4 border-b border-[var(--border)] pb-6 sm:flex-row sm:items-center sm:justify-between p-6">
            <div>
              <CardTitle className="text-base font-bold tracking-tight text-[var(--text)]">Sitemap</CardTitle>
              <CardDescription className="text-xs text-[var(--muted)] mt-0.5">Control what appears on the public sitemap page.</CardDescription>
            </div>
            <button
              type="button"
              onClick={() => saveTab("sitemap", "Sitemap")}
              disabled={savingTab === "sitemap"}
              className="inline-flex h-10 items-center justify-center rounded-xl bg-[var(--color-primary)] hover:bg-[var(--color-primary-hover)] px-5 text-xs font-bold text-white shadow-sm transition-all duration-200 cursor-pointer disabled:opacity-60 flex-shrink-0"
            >
              {savingTab === "sitemap" ? "Saving…" : "Save"}
            </button>
          </CardHeader>
          <CardContent className="p-6 grid gap-5 md:grid-cols-2">
            <FieldRow label="Page Title">
              <StyledInput value={content.sitemap.title} onChange={(e) => update("sitemap", "title", e.target.value)} placeholder="Sitemap" />
            </FieldRow>
            <FieldRow label="Subtitle">
              <StyledInput value={content.sitemap.subtitle} onChange={(e) => update("sitemap", "subtitle", e.target.value)} placeholder="Find everything on Couponchy." />
            </FieldRow>
            <div className="md:col-span-2 grid gap-3">
              <ToggleRow
                label="Show Stores Section"
                description="Auto-lists all stores from the database."
                checked={Boolean(content.sitemap.showAutoGeneratedStores)}
                onChange={(e) => update("sitemap", "showAutoGeneratedStores", e.target.checked)}
              />
              <ToggleRow
                label="Show Categories Section"
                description="Auto-lists all categories from the database."
                checked={Boolean(content.sitemap.showAutoGeneratedCategories)}
                onChange={(e) => update("sitemap", "showAutoGeneratedCategories", e.target.checked)}
              />
              <ToggleRow
                label="Show Blog Section"
                description="Auto-lists all published blog posts."
                checked={Boolean(content.sitemap.showBlogSection)}
                onChange={(e) => update("sitemap", "showBlogSection", e.target.checked)}
              />
            </div>
          </CardContent>
        </Card>
      ) : null}
    </div>
  );
}
